In [1]:
from log_helper.log_helper import LogHelper
from datetime import datetime
from pytz import timezone

import os
import pathlib
import logging

In [2]:
##################################################################################################
# Setup logger and output dir                                                                    #
##################################################################################################
output_dir = 'log/test-{}'.format(datetime.now(timezone('Asia/Seoul')).strftime('%Y-%m-%d_%H-%M-%S-%f')[:-3])
if not os.path.exists(output_dir):
    pathlib.Path(output_dir).mkdir(parents=True, exist_ok=True)

# Setup logger
LogHelper.setup(log_path='{}/test.log'.format(output_dir), log_level=logging.INFO)
_logger = logging.getLogger(__name__)

2019-07-04 11:34:52,318 INFO - log_helper.log_helper - Finished configuring logger


In [2]:
import numpy as np

In [3]:
from dataset import Dataset

In [4]:
X = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29, 30]
])

In [5]:
dataset = Dataset(X)

In [6]:
dataset.standard_scaler.transform(X)

array([[-1.41421356, -1.41421356, -1.41421356, -1.41421356, -1.41421356,
        -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678, -0.70710678, -0.70710678,
        -0.70710678],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.70710678,  0.70710678,  0.70710678,  0.70710678,  0.70710678,
         0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356,  1.41421356,  1.41421356,
         1.41421356]])

In [7]:
dataset.robust_scaler.transform(X)

array([[-1. , -1. , -1. , -1. , -1. , -1. ],
       [-0.5, -0.5, -0.5, -0.5, -0.5, -0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 1. ,  1. ,  1. ,  1. ,  1. ,  1. ]])

In [8]:
dataset.data

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [9]:
np.append(X, X).reshape(12, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
dataset.data = np.append(X, X).reshape(12, 5)

In [11]:
dataset.standard_scaler.transform(np.append(X, X).reshape(12, 5))

array([[-1.46385011, -1.46385011, -1.46385011, -1.46385011, -1.46385011],
       [-0.87831007, -0.87831007, -0.87831007, -0.87831007, -0.87831007],
       [-0.29277002, -0.29277002, -0.29277002, -0.29277002, -0.29277002],
       [ 0.29277002,  0.29277002,  0.29277002,  0.29277002,  0.29277002],
       [ 0.87831007,  0.87831007,  0.87831007,  0.87831007,  0.87831007],
       [ 1.46385011,  1.46385011,  1.46385011,  1.46385011,  1.46385011],
       [-1.46385011, -1.46385011, -1.46385011, -1.46385011, -1.46385011],
       [-0.87831007, -0.87831007, -0.87831007, -0.87831007, -0.87831007],
       [-0.29277002, -0.29277002, -0.29277002, -0.29277002, -0.29277002],
       [ 0.29277002,  0.29277002,  0.29277002,  0.29277002,  0.29277002],
       [ 0.87831007,  0.87831007,  0.87831007,  0.87831007,  0.87831007],
       [ 1.46385011,  1.46385011,  1.46385011,  1.46385011,  1.46385011]])

In [12]:
dataset.robust_scaler.transform(np.append(X, X).reshape(12, 5))

array([[-0.83333333, -0.83333333, -0.83333333, -0.83333333, -0.83333333],
       [-0.5       , -0.5       , -0.5       , -0.5       , -0.5       ],
       [-0.16666667, -0.16666667, -0.16666667, -0.16666667, -0.16666667],
       [ 0.16666667,  0.16666667,  0.16666667,  0.16666667,  0.16666667],
       [ 0.5       ,  0.5       ,  0.5       ,  0.5       ,  0.5       ],
       [ 0.83333333,  0.83333333,  0.83333333,  0.83333333,  0.83333333],
       [-0.83333333, -0.83333333, -0.83333333, -0.83333333, -0.83333333],
       [-0.5       , -0.5       , -0.5       , -0.5       , -0.5       ],
       [-0.16666667, -0.16666667, -0.16666667, -0.16666667, -0.16666667],
       [ 0.16666667,  0.16666667,  0.16666667,  0.16666667,  0.16666667],
       [ 0.5       ,  0.5       ,  0.5       ,  0.5       ,  0.5       ],
       [ 0.83333333,  0.83333333,  0.83333333,  0.83333333,  0.83333333]])