In [20]:
import numpy as np
import csv
import scipy.stats as scStat

with open('../data/fifa19.csv', 'r') as f:
    reader = csv.reader(f)
    X = list(reader)
del X[0]

X = np.array(X)
print(X[0])

['158023' 'L. Messi' '31' 'Argentina' '94' '94' 'FC Barcelona' '110.5'
 '565' '2202' 'Left' '5' '4' '4' 'Medium' 'Medium' 'Messi' 'Yes' 'RF' '67'
 '159' '90' '90' '90' '94' '95' '95' '95' '94' '95' '95' '95' '93' '86'
 '86' '86' '93' '66' '63' '63' '63' '66' '61' '49' '49' '49' '61' '84'
 '95' '70' '90' '86' '97' '93' '94' '87' '96' '91' '86' '91' '95' '95'
 '85' '68' '72' '59' '94' '48' '22' '94' '94' '75' '96' '33' '28' '26' '6'
 '11' '15' '14' '8' '226.5']


In [6]:
len(X)

18207

In [5]:
X.shape[1]

82

In [7]:
len(np.unique(X[:, 18]))

28

In [9]:
count = 0
for item in X[0]:
    if type(item) is not str:
        count += 1
count

82

In [11]:
count = 0
for sublist in X:
    for value in sublist:
        if not value:
            count += 1
count

2221

In [16]:
num = len(X) * len(X[0])
print(num)

1492974


In [37]:
X_numeric_ex = [[float(value[2]), float(value[4]), float(value[5]), float(value[19]), float(value[20])] for value in X]
skewness = scStat.skew(X_numeric_ex)
print(skewness)
print(min(skewness))
print(max(skewness))
print(np.median(skewness))
print(np.mean(skewness))
print(np.percentile(skewness, 25))
print(np.percentile(skewness, 75))

[  0.39173186   0.06717939   0.26613167 -10.28217888  -1.93639701]
-10.282178884321816
0.39173186219064426
0.06717938706202287
-2.298706594708471
-1.936397007051656
0.2661316685784485


In [39]:
#kurtosis = scStat.kurtosis(X_numeric_ex)
print(kurtosis)

[-4.59716898e-01  9.62126239e-02  3.54864452e-02  1.60017978e+02
  1.88159881e+01]


In [44]:
X_numeric_ex = np.array(X_numeric_ex)
corr = np.corrcoef(X_numeric_ex.T)
print(corr)
print(corr.shape)

[[ 1.          0.45234952 -0.25331211  0.04943658  0.20241583]
 [ 0.45234952  1.          0.66093854  0.04813651  0.15075077]
 [-0.25331211  0.66093854  1.          0.02463824  0.01189186]
 [ 0.04943658  0.04813651  0.02463824  1.          0.77667253]
 [ 0.20241583  0.15075077  0.01189186  0.77667253  1.        ]]
(5, 5)


In [65]:
for i in range(len(corr)):
    corr[i][i] = 0
    
print(corr)

[[ 0.          0.45234952 -0.25331211  0.04943658  0.20241583]
 [ 0.45234952  0.          0.66093854  0.04813651  0.15075077]
 [-0.25331211  0.66093854  0.          0.02463824  0.01189186]
 [ 0.04943658  0.04813651  0.02463824  0.          0.77667253]
 [ 0.20241583  0.15075077  0.01189186  0.77667253  0.        ]]
